[build]
  publish = "public"
  functions = "functions"

  # Firebase 환경 변수 추가
  [build.environment]
    apiKey: "AIzaSyBe3wWDbyLvPvzHTtvpnXnJNlDOqEVlHNU",
    authDomain: "mornig-qt.firebaseapp.com",
    projectId: "mornig-qt",
    storageBucket: "mornig-qt.appspot.com",
    messagingSenderId: "1083392972716",
    appId: "1:1083392972716:web:f359cdd776f0c0d7fb4c09",
    measurementId: "G-FW5QEZPB5H"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
